// Writes NEEDED_ZIPS.md: for every recipe in recipes/, the zips its picks
// come from. Run with `npm run needed-zips` after merging new recipes.
const fs = require("fs");
const path = require("path");
const { loadBundledSchema } = require("../src/core/schema");
const { validateRecipe, neededZipsText } = require("../src/core/recipe");

const root = path.join(__dirname, "..", "recipes");
const files = [];
(function walk(dir) {
  for (const n of fs.readdirSync(dir).sort()) {
    const p = path.join(dir, n);
    if (fs.statSync(p).isDirectory()) walk(p); else if (n.endsWith(".json")) files.push(p);
  }
})(root);

const sections = [
  "# Zips needed for each recipe",
  "",
  "Generated by `npm run needed-zips` from the recipes in `recipes/`. Each recipe lists the zips its picks come from. Download those zips yourself, add them in the packager, and the recipe fills the pack.",
  "",
];
for (const f of files) {
  const raw = JSON.parse(fs.readFileSync(f, "utf8"));
  const { recipe } = validateRecipe(raw, loadBundledSchema(raw.mod_id));
  const body = neededZipsText(recipe).replace(/^# /m, "## ").replace(/^## (?!Zips needed)/gm, "### ");
  sections.push(body.trim(), "", `Recipe file: \`${path.relative(path.join(__dirname, ".."), f).split(path.sep).join("/")}\``, "");
}
const out = path.join(__dirname, "..", "NEEDED_ZIPS.md");
fs.writeFileSync(out, sections.join("\n"));
console.log(`wrote ${path.basename(out)} for ${files.length} ${files.length === 1 ? "recipe" : "recipes"}`);
